/** Single source for partner logos — used on Clients and home brands marquee */
export const partnerLogos = [
  { name: "Sun Pharma", src: "/images/SUN PHARMA.jpg" },
  { name: "Cipla", src: "/images/Cipla_logo.svg" },
  { name: "Bharat Biotech", src: "/images/bharat-biotech-logo.jpg" },
  { name: "Abbott", src: "/images/Abbott_Laboratories_logo.svg" },
  { name: "GSK", src: "/images/GSK_logo_2014.svg.png" },
  { name: "Partner Logo", src: "/images/logo.png" },
  { name: "Partner Logo", src: "/images/images.png" },
  { name: "Partner Logo", src: "/images/images (1).png" },
  { name: "Partner Logo", src: "/images/images (2).png" },
  { name: "Partner Logo", src: "/images/images (3).png" },
  { name: "Partner Logo", src: "/images/images (4).png" },
  { name: "Partner Logo", src: "/images/images (5).png" },
  { name: "Partner Logo", src: "/images/images (6).png" },
  { name: "MSN Labs", src: "/images/MSN.png" },
  { name: "IPCA", src: "/images/IPCA.png" },
  { name: "Mankind", src: "/images/Mankind.png" },
  { name: "Galderma", src: "/images/Galderma_logo.svg.png" },
  { name: "JB Chemicals", src: "/images/JB.png" },
  { name: "Alkem", src: "/images/ALKEM.png" },
  { name: "Torrent Pharmaceuticals", src: "/images/Torrent-Pharmaceuticals-Ltd-1.jpeg" },
  { name: "Aristo", src: "/images/ARISTO.png" },
  { name: "Macleods", src: "/images/Macleods.jpg" },
  { name: "Alembic", src: "/images/alembic_logo.jpeg" },
] as const;
